site_name: Trailarr Docs
site_url: https://nandyalu.github.io/trailarr
site_description: Trailarr is a simple, lightweight, and easy-to-use media server for your personal media collection.
repo_name: nandyalu/trailarr
repo_url: https://github.com/nandyalu/trailarr
theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
  logo: https://raw.githubusercontent.com/nandyalu/trailarr/main/assets/images/trailarr-512.png
  favicon: https://raw.githubusercontent.com/nandyalu/trailarr/main/assets/images/trailarr-48.png
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - navigation.tabs
    - navigation.instant
    - navigation.instant.progress
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - search.suggest
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
  - search
  - git-revision-date-localized
  # - swagger-ui-tag
  - mkdocs_github_changelog:
        # token: !ENV GITHUB_TOKEN
        # Github token (needs repo scope for private repos, and may be worth setting for public repos due to rate limiting).
        # github_api_url: <url>
        # URL for github api endpoint if not standard github.com (This is not tested on github enterprise server).
        # release_template: <jinja2 str>
        # Jinja2 template string to override the default. 
        # match: '[0-9+].[0-9+].[0-9]+'
        # Regex string for matching the rleease name.
        # autoprocess: True
        # Autoprocess the body for user and issue/pull request links
        enabled: True
        # Enable or disable the plugin.
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - md_in_html
extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/nandyalu/trailarr
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/nandyalu/trailarr
    - icon: fontawesome/brands/reddit-alien
      link: https://www.reddit.com/r/trailarr
    - icon: fontawesome/brands/discord
      link: https://discord.gg/BAJsv76N
nav:
  - Trailarr: index.md
  - Install:
    - Install: install.md
    - Environment Variables: install/env-variables.md
    - Volume Mapping: install/volume-mapping.md
    - Docker Compose: install/docker-compose.md
    - Docker Run: install/docker-cli.md
    # - Docker Builder: install/docker-builder.md
    # - Usage: install/form.html
  - Setup:
    - Connections: setup/connections.md
    - Settings: setup/settings.md
  - Help:
    - Common: help/common.md
    - FAQ: help/faq.md
    - Release Notes: help/release-notes.md
    # - Changelog: help/changelog.md
    - Docker Builder: help/docker-builder/builder.html
# extra_javascript:
#   - js/docker-builder.js