"""beta plex

Revision ID: 8279ed671783
Revises: 1cc1dd5dbe9f
Create Date: 2024-12-14 20:56:27.640260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlmodel.sql.sqltypes
from app_logger import ModuleLogger


# revision identifiers, used by Alembic.
revision: str = '8279ed671783'
down_revision: Union[str, None] = '1cc1dd5dbe9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

logging = ModuleLogger("AlembicMigrations")


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plex_rating_key', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plex_trailer_exists', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_column('plex_trailer_exists')
        batch_op.drop_column('plex_rating_key')

    # ### end Alembic commands ###
